---
- name: Ensure required packages are present
  ansible.builtin.package:
    name:
      - audit
      - curl
    state: present

- name: Create configuration directory
  ansible.builtin.file:
    path: /etc/foreman-config-tracker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy tracker.conf
  ansible.builtin.template:
    src: tracker.conf.j2
    dest: /etc/foreman-config-tracker/tracker.conf
    owner: root
    group: root
    mode: '0640'

- name: Deploy forwarder script
  ansible.builtin.template:
    src: foreman-config-forwarder.sh.j2
    dest: /usr/local/bin/foreman-config-forwarder.sh
    mode: '0750'
    owner: root
    group: root

- name: Deploy dispatcher plugin
  ansible.builtin.template:
    src: foreman-config-forwarder.conf.j2
    dest: /etc/audisp/plugins.d/foreman-config-forwarder.conf
    owner: root
    group: root
    mode: '0644'

- name: Deploy audit rules file
  ansible.builtin.template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/foreman-config-tracker.rules
    owner: root
    group: root
    mode: '0640'
  notify:
    - reload auditd
    - restart auditd

- name: Ensure auditd is enabled and running
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: true
